name: Build kernel

on:
  push:
    branches:
      - susfstest

  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build (manual trigger)'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/susfstest'  # only runs if on the 'susfstest' branch
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools ccache

      - name: Build Kernel
        run: |
          chmod +x ./build.sh
          ./build.sh -m z3s -k y -r n

      - name: Find built zips
        id: find_zips
        run: |
          ZIP_FILES=$(find . -type f -name "*.zip")
          if [[ -z "$ZIP_FILES" ]]; then
            echo "No ZIPs found! Exiting."
            exit 1
          fi
          echo "ZIP_FILES<<EOF" >> $GITHUB_ENV
          echo "$ZIP_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload built kernels
        uses: actions/upload-artifact@v4
        with:
          name: built-kernels
          path: ${{ env.ZIP_FILES }}
